Hopital-env/Gestion_Rendez_Vous/Gestion_Rendez_Vous/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Rendez_Vous.urls')),
    
]

Hopital-env/Gestion_Rendez_Vous/Rendez_Vous/urls.py
from django.urls import path, include
#from django.contrib.auth import views as auth_views

from Rendez_Vous.views import liste_rendezvous,liste_patient,enregistrer_rendez_vous,modifier_rdv,supprimer_rdv,details_rdv,ajouter_patient, supprimer_patient, modifier_patient,details_patients, index,inscription, connexion,deconnexion
from django.contrib.auth import views


urlpatterns=[
    path('rendezvous/',liste_rendezvous, name='rendezvous'),
    path('liste_patient/', liste_patient, name='liste_patient'),
    path('enregistrer_rendez_vous/', enregistrer_rendez_vous, name='enregistrer_rendez_vous'),
    path('modifier/<int:id>', modifier_rdv, name='modifier'),
    path('supprimer_rdv/<int:id>', supprimer_rdv, name='supprimer_rdv'),
    path('details_rdv/<int:id>', details_rdv, name='details_rdv'),
    path('ajouter_patient/', ajouter_patient, name='ajouter_patient'),
    path('supprimer_patient/<int:id>', supprimer_patient, name='supprimer_patient'),
    path('modifier_patient/<int:id>', modifier_patient, name='modifier_patient'),
    path('details_patient/<int:id>', details_patients, name='details_patients'),
    path('', index, name='index'),
    path('inscription/', inscription, name='inscription'),
    path('accounts/login/', connexion, name='connexion'),
    path('deconnexion/', deconnexion, name='deconnexion'),
    path('reset_password/',views.PasswordResetView.as_view(template_name='password_reset.html'),name='reset_password'),
    path('reset_password_send/',views.PasswordResetDoneView.as_view(template_name='password_reset_send.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',views.PasswordResetConfirmView.as_view(template_name='password_reset_form.html'),name='password_reset_confirm'),
    path('reset_password_complete/',views.PasswordResetCompleteView.as_view(template_name='password_confirm.html'),name='password_reset_complete'),
    
    #path('accounts/',include('django.contrib.auth.urls'))
    #path('enregistrer_rdv_patient/<int:id>', enregistrer_rdv_patient, name='enregistrer_rdv_patient')


]
   

Hopital-env/Gestion_Rendez_Vous/Rendez_Vous/models.py
from django.db import models
class Patient(models.Model):
    nom=models.CharField(max_length=100)
    prenom=models.CharField(max_length=100)
    age=models.PositiveIntegerField()
    numtel=models.CharField(max_length=20)
    motif=models.TextField()
    def __str__(self):
        return f" {self.nom} {self.prenom}"
    

"""class Medecin(models.Model):
    nom=models.CharField(max_length=100)
    prenom=models.CharField(max_length=100)
    specialite=models.CharField(max_length=100)"""
    


    
class Rendez_vous(models.Model):
    patient=models.ForeignKey(Patient, on_delete=models.CASCADE)
    date=models.DateField()
    heure=models.TimeField()

    def __str__(self):
        return f"Rendez-vous pour {self.patient.nom} le {self.date} à {self.heure}"
    



    

Hopital-env/Gestion_Rendez_Vous/Rendez_Vous/forms.py
from django import forms
from . models import Patient, Rendez_vous
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class PatientForms(forms.ModelForm):
    class Meta:
        model=Patient
        fields='__all__'

class RendezvousForm(forms.ModelForm):
    class Meta:
        model=Rendez_vous
        fields='__all__'
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'heure': forms.TimeInput(attrs={'type': 'time', 'class': 'form-control'}),
            'patient': forms.Select(attrs={'class': 'form-control'}),
        }


"""class UserForm(UserCreationForm):
    
    class Meta:
        model=User
        fields=[
            'username',
            'last_name',
            'email',
            'password1',
            'password2'
        ]
    from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User"""

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'last_name', 'email', 'password1', 'password2']

    widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        }

Hopital-env/Gestion_Rendez_Vous/Rendez_Vous/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . models import Patient, Rendez_vous
from . forms import PatientForms,RendezvousForm, UserForm
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages


@login_required
def liste_rendezvous(request):
    rendez_vous=Rendez_vous.objects.all()
    return render(request, 'liste_rendezvous.html', {'rendez_vous':rendez_vous})

@login_required
def liste_patient(request):
    patients=Patient.objects.all()
    item_submit=request.GET.get('item-submit')
    # rechercher par le nom du patient
    if item_submit != '' and item_submit is not None:
        
        patients=Patient.objects.filter(nom__icontains=item_submit)
    
        
    return render(request, 'liste_patient.html', {'patients':patients})

@login_required
def enregistrer_rendez_vous(request):
    form=RendezvousForm()
    if request.method=='POST':
        form=RendezvousForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('rendezvous')
    else:
        form=RendezvousForm()
    return render(request, 'rendezvousform.html', {'form':form})


"""def enregistrer_rdv_patient(request, id):
    patient=Patient.objects.get(id=id)
    if request.method == 'POST':
        form = RendezvousForm(request.POST)
        if form.is_valid():
            rendezvous = form.save(commit=False)
            rendezvous.patient = patient
            rendezvous.save()
            return redirect('rendezvous', id=patient.id)
    else:
        form=RendezvousForm(initial={'patient': patient})
    return render(request, 'addrdvparID.html',{'form':form, 'patient':patient})"""

@login_required
def modifier_rdv(request, id):
    rendezvous=Rendez_vous.objects.get(id=id)
    if request.method=='POST':
        form=RendezvousForm(request.POST, instance=rendezvous)
        if form.is_valid():
            form.save()
            return redirect('rendezvous')
    else:
        form=RendezvousForm(instance=rendezvous)
        return render(request, 'modifier_rdv.html', {'form':form})
    
@login_required
def supprimer_rdv(request, id):
    rendezvous=Rendez_vous.objects.get(id=id)
    if request.method=='POST':
        rendezvous.delete()
        return redirect('rendezvous')
    return render(request, 'confirmer_supprdv.html', {'rendezvous':rendezvous})

@login_required
def details_rdv(request, id):
    rendezvous=Rendez_vous.objects.get(id=id)
    return render(request, 'details_rdv.html', {'rendezvous':rendezvous})

@login_required
def ajouter_patient(request):
    fors=PatientForms()
    if request.method=='POST':
        fors=PatientForms(request.POST)
        fors.save()
        return redirect('liste_patient')
    return render(request, 'ajouter_patient.html', {'fors': fors})

@login_required
def supprimer_patient(request, id):
    patient=Patient.objects.get(id=id)
    if request.method=='POST':
        patient.delete()
        return redirect('liste_patient')
    return render(request, 'supprimer_patient.html', {'patient':patient})

@login_required
def modifier_patient(request, id):
    patient=Patient.objects.get(id=id)
    if request.method=='POST':
        fors=PatientForms(request.POST, instance=patient)
        if fors.is_valid():
            fors.save()
            return redirect('liste_patient')
    else:
        fors=PatientForms(instance=patient)
        return render(request, 'modifier_patient.html', {'fors':fors})
    

@login_required
def details_patients(request, id):
    patient=Patient.objects.get(id=id)
    return render(request,'details_patient.html', {'patient':patient})


def index(request):
    return render(request, 'index.html')


def inscription(request):
    form=UserForm()
    if request.method=='POST':
        form=UserForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Votre inscription a bien réussi')
            return redirect('connexion')
        else:
            messages.error(request, form.errors)
    return render(request, 'inscription.html', {'form':form})


def connexion(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=authenticate(request, username=username, password=password)
        if user is not None and user.is_active:
            login(request, user)
            messages.success(request, 'Authentification réussi avec succés')
            return redirect('liste_patient')
        else:
            messages.error(request, 'Erreur d\'authentification')
    return render(request, 'login.html')


@login_required
def deconnexion(request):
    logout(request)
    return redirect('connexion')




    







    

# Create your views here.

Hopital-env/Gestion_Rendez_Vous/Rendez_Vous/templates/addrdvparID.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter un Rendez-vous</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h2>Ajouter un Rendez-vous pour {{ patient.nom }} {{ patient.prenom }}</h2>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_date" class="form-label">Date</label>
                {{ form.date }}
                {% if form.date.errors %}
                    <div class="text-danger">{{ form.date.errors }}</div>
                {% endif %}
            </div>
            <div class="mb-3">
                <label for="id_heure" class="form-label">Heure</label>
                {{ form.heure }}
                {% if form.heure.errors %}
                    <div class="text-danger">{{ form.heure.errors }}</div>
                {% endif %}
            </div>
            <button type="submit" class="btn btn-primary">Enregistrer</button>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Hopital-env/Gestion_Rendez_Vous/Rendez_Vous/templates/ajouter_patient.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <style>
        h1 {
            text-align: center;
            background-color: #85C1E9;
            color: #fff;
            border: none;
            border-radius: 5px;
            width: 100%;
        }
        body {
            font-family: Arial, Helvetica, sans-serif;
        
    
        }
    
        form {
            max-width: 500px;
            margin: 0 auto;
            padding: 50px;
            background-color: #f9f9f9;
            border:none;
            border-radius: 4px;
        
        }
    
        input[type='text'],input[type="number"],
        textarea {
            overflow: hidden;
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc; 
            border-radius: 4px;
            margin-bottom: 10px;
    
        }
    
        input[type="submit"] {
            background-color:#85C1E9;
            color: #ffff;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
            border: none;
        }
    
       
        label {
            font-weight: bold;
            display: block;
            margin-bottom: 5px;
        }
    
        select {
            width: 100%;
            padding: 10px 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
            margin-bottom: 10px;
        }
    
        select option {
            background-color: #fff;
            color: #000;
            font-weight: bold;
            font-size: 10px;
            
        }

        button {
            background-color: #85C1E9;
            
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
            border: none;
            float: right;
            
            
        }
        button[type="submit"]{
            padding: 10px 20px; 
            float:left;
            background-color:#85C1E9;
            padding-bottom:2px,2px;
            color:#fff;
        }

        button:hover {
            float:left;
            background-color:#85C1E9;
            padding-bottom:2px,2px;
            color:#fff;
        }
        .lien { 
            float:left;
            background-color:#85C1E9;
            padding-bottom:2px,2px;
            color: #fff;
            text-decoration:none;
            margin-left: 10px;
            margin-right: 10px;
        }


    </style>
    
    <form action="" method="post">
        {% csrf_token %}
        {{fors.as_p}}
        <button type="submit">Enregistrer</button>
        <button><a class="lien" href="{% url 'liste_patient'%}">Annuler</a></button>
    </form>
    

</body>
</html>

Hopital-env/Gestion_Rendez_Vous/Rendez_Vous/templates/details_patient.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Détail du Patient</title>
    <link rel="stylesheet" href="{% static 'CSS/style.css' %}">
</head>
<body>
    <div class="patient-detail-container">
        <h1>Détails du Patient</h1>
        <div class="patient-info">
            <p><strong>Nom:</strong> {{ patient.prenom }} {{ patient.nom }}</p>
            <p><strong>ID:</strong> {{ patient.id }}</p>
            <p><strong>Age:</strong> {{ patient.age}}</p>
            <p><strong>Numéro de téléphone:</strong> {{ patient.numtel }}</p>
            <p><strong>motif:</strong> {{ patient.motif }}</p>
        </div>
    </div>
</body>
</html>

Hopital-env/Gestion_Rendez_Vous/Rendez_Vous/templates/details_rdv.html
{%load static%}
<link rel="stylesheet" href="{%static 'CSS/style.css'%}">

<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <div class="card card-margin">
                <div class="card-header no-border">

                    <h5 class="card-title">{{rendezvous.patient}}</h5>
                </div>
                <div class="card-body pt-0">
                    <div class="widget-49">
                        <div class="widget-49-title-wrapper">
                            <div class="widget-49-date-primary">
                                <span class="widget-49-date-day">{{rendezvous.id}}</span>
                                <span class="widget-49-date-month"></span>
                            </div>
                            <div class="widget-49-meeting-info">
                                <span class="widget-49-pro-title">{{rendezvous.date}}</span>
                                <span class="widget-49-meeting-time">{{rendezvous.heure}}</span>
                            </div>
                        </div>
                        <ol class="widget-49-meeting-points">
                            <li class="widget-49-meeting-item"><span>{{rendezvous.patient.motif}}</span></li>
                            <li class="widget-49-meeting-item"><span>Age du patient:{{rendezvous.patient.age}}</span></li>
                            <li class="widget-49-meeting-item"><span>Teléphone: {{rendezvous.patient.numtel}} ans</span></li>
                        </ol>
                        <div class="widget-49-meeting-action">
                            <a href="{% url 'rendezvous' %}" class="btn btn-sm btn-flash-border-primary">Retourner</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        </div>
    </div>
    </div>

Hopital-env/Gestion_Rendez_Vous/Rendez_Vous/templates/inscription.html
<!DOCTYPE html>
{% extends 'base.html'%}

{%block content%}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inscription</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
</head>
{% load widget_tweaks %}

<body>
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2 class="mb-4 text-center">Créer un compte</h2>
                <form method="post" action="{% url 'inscription' %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="{{ form.username.id_for_label }}" class="form-label">Nom d'utilisateur</label>
                        <div class="input-group">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                            {{ form.username|add_class:"form-control" }}
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.last_name.id_for_label }}" class="form-label">Nom</label>
                        <div class="input-group">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                            {{ form.last_name|add_class:"form-control" }}
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.email.id_for_label }}" class="form-label">Adresse Email</label>
                        <div class="input-group">
                            <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                            {{ form.email|add_class:"form-control" }}
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.password1.id_for_label }}" class="form-label">Mot de passe</label>
                        <div class="input-group">
                            <span class="input-group-text"><i class="fas fa-lock"></i></span>
                            {{ form.password1|add_class:"form-control" }}
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.password2.id_for_label }}" class="form-label">Confirmez le mot de passe</label>
                        <div class="input-group">
                            <span class="input-group-text"><i class="fas fa-lock"></i></span>
                            {{ form.password2|add_class:"form-control" }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary w-100">Créer un compte</button>
                </form>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

{%endblock%}

Hopital-env/Gestion_Rendez_Vous/Rendez_Vous/templates/liste_patient.html
<!DOCTYPE html>
{% extends 'base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Liste des patients</title>
</head>
{% block content %}
<body>
    {%csrf_token%}
    <h1>Liste des patients: <button><a class="col" href="{% url 'ajouter_patient' %}"><svg width="40" height="40" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
        <path fill="#70bf2b" d="M1600 796v192q0 40-28 68t-68 28h-416v416q0 40-28 68t-68 28h-192q-40 0-68-28t-28-68v-416h-416q-40 0-68-28t-28-68v-192q0-40 28-68t68-28h416v-416q0-40 28-68t68-28h192q40 0 68 28t28 68v416h416q40 0 68 28t28 68z"/>
      </svg>
      </a></button></h1>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #0a0b0c;
        }

        th {
            background-color: #070809;
            color:#fff;
        }

       
        button {
            background-color: #fff;
            color: #fff;
            text-decoration: none;
        }
        .col {
            color:#fff;
            text-decoration: none;
        }
        .paf {
            color: #fff;
            text-decoration: none;
        }
    </style>
    
    <table class="table">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>PRENOM</th>
                <th>NOM</th>
                <th>AGE</th>
                <th>TELEPHONE</th>
                <th>MOTIFS</th>
                <th>ACTIONS</th>

            </tr>
        </thead>
        <tbody>
            
            {%for patient in patients%}
                <tr>
                    <td>{{patient.id}}</td>
                    <td>{{patient.prenom}}</td>
                    <td>{{patient.nom}}</td>
                    <td>{{patient.age}}</td>
                    <td>{{patient.numtel}}</td>
                    <td>{{patient.motif}}</td>
                    <td>
                        <button><a class="paf" href="{% url 'modifier_patient' patient.id %}"><svg width="20" height="20" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                            <path fill="#efb80b" d="M491 1536l91-91-235-235-91 91v107h128v128h107zm523-928q0-22-22-22-10 0-17 7l-542 542q-7 7-7 17 0 22 22 22 10 0 17-7l542-542q7-7 7-17zm-54-192l416 416-832 832h-416v-416zm683 96q0 53-37 90l-166 166-416-416 166-165q36-38 90-38 53 0 91 38l235 234q37 39 37 91z"/>
                          </svg>
                          </a></button>
                        <button><a class="paf" href="{% url 'supprimer_patient' patient.id %}"><svg width="20" height="20" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                            <path fill="#dd4646" d="M1490 1322q0 40-28 68l-136 136q-28 28-68 28t-68-28l-294-294-294 294q-28 28-68 28t-68-28l-136-136q-28-28-28-68t28-68l294-294-294-294q-28-28-28-68t28-68l136-136q28-28 68-28t68 28l294 294 294-294q28-28 68-28t68 28l136 136q28 28 28 68t-28 68l-294 294 294 294q28 28 28 68z"/>
                          </svg>
                          </a></button>
                        <button><a class="paf" href="{% url 'details_patients' patient.id %}"><svg width="20" height="20" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                            <path fill="#2b70bf" d="M1664 960q-152-236-381-353 61 104 61 225 0 185-131.5 316.5t-316.5 131.5-316.5-131.5-131.5-316.5q0-121 61-225-229 117-381 353 133 205 333.5 326.5t434.5 121.5 434.5-121.5 333.5-326.5zm-720-384q0-20-14-34t-34-14q-125 0-214.5 89.5t-89.5 214.5q0 20 14 34t34 14 34-14 14-34q0-86 61-147t147-61q20 0 34-14t14-34zm848 384q0 34-20 69-140 230-376.5 368.5t-499.5 138.5-499.5-139-376.5-368q-20-35-20-69t20-69q140-229 376.5-368t499.5-139 499.5 139 376.5 368q20 35 20 69z"/>
                          </svg>
                          </a></button>
                          
                    </td>
                </tr>
            {%endfor%}
        </tbody>
    </table>
    
</body>
</html>
{% endblock%}

Hopital-env/Gestion_Rendez_Vous/Rendez_Vous/templates/login.html
{%load static%}


<link rel="stylesheet" href="{%static 'bootstrap-5.3.3-dist/bootstrap-5.3.3-dist/css/bootstrap.min.css'%}">
<section class="vh-100" style="background-color: #ffffff;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-xl-10">
          <div class="card" style="border-radius: 1rem;">
            <div class="row g-0">
              <div class="col-md-6 col-lg-5 d-none d-md-block">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img1.webp"
                  alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
              </div>
              <div class="col-md-6 col-lg-7 d-flex align-items-center">
                <div class="card-body p-4 p-lg-5 text-black">
                    {% for message in messages%}
                      {% if message %}
                        <p style="color: red;">{{message}}</p>
                      {%else%}
                        <p style="color: green;">{{message}}</p>
                      {%endif%}
                    {% endfor %}
  
                  <form action="{% url 'connexion'%}" method="post">
                    {% csrf_token %}
  
                    <div class="d-flex align-items-center mb-3 pb-1">
                      <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                      <span class="h1 fw-bold mb-0">Logo</span>
                    </div>
  
                    <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Connectez-vous à votre compte</h5>
  
                    <div data-mdb-input-init class="form-outline mb-4">
                      <input type="text" id="form2Example17" class="form-control form-control-lg" name="username" required/>
                      <label class="form-label" for="form2Example17">Nom d'utilisateur</label>
                    </div>
  
                    <div data-mdb-input-init class="form-outline mb-4">
                      <input type="password" id="form2Example27" class="form-control form-control-lg" name="password" required/>
                      <label class="form-label" for="form2Example27">Mot de passe</label>
                    </div>
  
                    <div class="pt-1 mb-4">
                      <button data-mdb-button-init data-mdb-ripple-init class="btn btn-dark btn-lg btn-block" type="submit">Se connecter</button>
                    </div>
  
                    <a class="small text-muted" href="/reset_password">mot de passe oublié?</a>
                    <p class="mb-5 pb-lg-2" style="color: #393f81;">Vous n'avez pas de compte? <a href="{% url 'inscription'%}"
                        style="color: #393f81;">Inscrivez-vous ici</a></p>
                  </form>
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<script src="{% static 'bootstrap-5.3.3-dist/bootstrap-5.3.3-dist/js/bootstrap.min.js'%}"></script>

Hopital-env/Gestion_Rendez_Vous/Rendez_Vous/templates/password_confirm.html
<h1>Votre mot de passe a été réinitialisé avec succés</h1>
<a href="{% url 'connexion'%}">Quitter</a>

Hopital-env/Gestion_Rendez_Vous/Rendez_Vous/templates/rendezvousform.html
<!DOCTYPE html>
<html lang="en">
{%extends 'base.html'%}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter un Rendez-vous</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
{%block content%}
<body>
    <div class="container mt-5">
        <h2 class="text-center">Ajouter un Rendez-vous</h2>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_patient" class="form-label">Patient</label>
                {{ form.patient }}
                {% if form.patient.errors %}
                    <div class="text-danger">{{ form.patient.errors }}</div>
                {% endif %}
            </div>
            <div class="mb-3">
                <label for="id_date" class="form-label">Date</label>
                {{ form.date }}
                {% if form.date.errors %}
                    <div class="text-danger">{{ form.date.errors }}</div>
                {% endif %}
            </div>
            <div class="mb-3">
                <label for="id_heure" class="form-label">Heure</label>
                {{ form.heure }}
                {% if form.heure.errors %}
                    <div class="text-danger">{{ form.heure.errors }}</div>
                {% endif %}
            </div>
            <button type="submit" class="btn btn-primary">Enregistrer</button>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
{%endblock%}
</html>